package serverhost;

/**
 *
 * @author dam1
 */
public class VServer extends javax.swing.JFrame {

    /**
     * Creates new form VServer
     */
    public VServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        PanelServer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelMensajes = new javax.swing.JPanel();
        LabelTXTMsg = new javax.swing.JPanel();
        LabelSendMsg = new javax.swing.JPanel();
        BtnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyChat Host");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 600));
        setSize(new java.awt.Dimension(850, 600));

        bg.setBackground(new java.awt.Color(177, 166, 192));
        bg.setMinimumSize(new java.awt.Dimension(850, 600));
        bg.setPreferredSize(new java.awt.Dimension(850, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelServer.setBackground(new java.awt.Color(236, 243, 226));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Servidor");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout PanelServerLayout = new javax.swing.GroupLayout(PanelServer);
        PanelServer.setLayout(PanelServerLayout);
        PanelServerLayout.setHorizontalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        PanelServerLayout.setVerticalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(PanelServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 120, 40));

        PanelMensajes.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout PanelMensajesLayout = new javax.swing.GroupLayout(PanelMensajes);
        PanelMensajes.setLayout(PanelMensajesLayout);
        PanelMensajesLayout.setHorizontalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanelMensajesLayout.setVerticalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        bg.add(PanelMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 750, 390));

        LabelTXTMsg.setBackground(new java.awt.Color(248, 248, 248));
        LabelTXTMsg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        LabelTXTMsg.setForeground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout LabelTXTMsgLayout = new javax.swing.GroupLayout(LabelTXTMsg);
        LabelTXTMsg.setLayout(LabelTXTMsgLayout);
        LabelTXTMsgLayout.setHorizontalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        LabelTXTMsgLayout.setVerticalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(LabelTXTMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 650, 40));

        LabelSendMsg.setBackground(new java.awt.Color(236, 243, 226));
        LabelSendMsg.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N

        BtnEnviar.setBackground(new java.awt.Color(236, 243, 226));
        BtnEnviar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        BtnEnviar.setForeground(new java.awt.Color(51, 51, 51));
        BtnEnviar.setText("Enviar");
        BtnEnviar.setBorder(null);
        BtnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LabelSendMsgLayout = new javax.swing.GroupLayout(LabelSendMsg);
        LabelSendMsg.setLayout(LabelSendMsgLayout);
        LabelSendMsgLayout.setHorizontalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        LabelSendMsgLayout.setVerticalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(LabelSendMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JPanel LabelSendMsg;
    private javax.swing.JPanel LabelTXTMsg;
    private javax.swing.JPanel PanelMensajes;
    private javax.swing.JPanel PanelServer;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
