
package easychat;


public class VCliente extends javax.swing.JFrame {

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        bg = new javax.swing.JPanel();
        PanelServer = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();
        LabelTXTMsg = new javax.swing.JPanel();
        txtMensaje = new javax.swing.JTextField();
        LabelSendMsg = new javax.swing.JPanel();
        BtnEnviar = new javax.swing.JButton();
        PanelMensajes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bandejaEntrada = new javax.swing.JTextArea();
        txtIP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        entryUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField2.setBackground(new java.awt.Color(177, 166, 192));
        jTextField2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Bienvenido");
        jTextField2.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyChat");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 650));
        setResizable(false);

        bg.setBackground(new java.awt.Color(177, 166, 192));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelServer.setBackground(new java.awt.Color(236, 243, 226));

        btnConectar.setBackground(new java.awt.Color(236, 243, 226));
        btnConectar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnConectar.setForeground(new java.awt.Color(51, 51, 51));
        btnConectar.setText("Conectar");
        btnConectar.setBorder(null);
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelServerLayout = new javax.swing.GroupLayout(PanelServer);
        PanelServer.setLayout(PanelServerLayout);
        PanelServerLayout.setHorizontalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelServerLayout.setVerticalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(PanelServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 120, 40));

        LabelTXTMsg.setBackground(new java.awt.Color(248, 248, 248));
        LabelTXTMsg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        LabelTXTMsg.setForeground(new java.awt.Color(248, 248, 248));

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(51, 51, 51));
        txtMensaje.setText("Introducir mensaje aqui");
        txtMensaje.setOpaque(true);
        txtMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelTXTMsgLayout = new javax.swing.GroupLayout(LabelTXTMsg);
        LabelTXTMsg.setLayout(LabelTXTMsgLayout);
        LabelTXTMsgLayout.setHorizontalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        LabelTXTMsgLayout.setVerticalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(LabelTXTMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 650, 40));

        LabelSendMsg.setBackground(new java.awt.Color(236, 243, 226));
        LabelSendMsg.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N

        BtnEnviar.setBackground(new java.awt.Color(236, 243, 226));
        BtnEnviar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        BtnEnviar.setForeground(new java.awt.Color(51, 51, 51));
        BtnEnviar.setText("Enviar");
        BtnEnviar.setBorder(null);
        BtnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelSendMsgLayout = new javax.swing.GroupLayout(LabelSendMsg);
        LabelSendMsg.setLayout(LabelSendMsgLayout);
        LabelSendMsgLayout.setHorizontalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LabelSendMsgLayout.setVerticalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(LabelSendMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 90, 40));

        PanelMensajes.setBackground(new java.awt.Color(248, 248, 248));

        bandejaEntrada.setBackground(new java.awt.Color(248, 248, 248));
        bandejaEntrada.setColumns(20);
        bandejaEntrada.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        bandejaEntrada.setRows(5);
        bandejaEntrada.setBorder(null);
        jScrollPane1.setViewportView(bandejaEntrada);

        javax.swing.GroupLayout PanelMensajesLayout = new javax.swing.GroupLayout(PanelMensajes);
        PanelMensajes.setLayout(PanelMensajesLayout);
        PanelMensajesLayout.setHorizontalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        PanelMensajesLayout.setVerticalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        bg.add(PanelMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 750, 390));

        txtIP.setBackground(new java.awt.Color(255, 255, 255));
        txtIP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIP.setBorder(null);
        bg.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("IP:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 40));

        entryUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        entryUsuario.setForeground(new java.awt.Color(51, 51, 51));
        entryUsuario.setAlignmentY(0.0F);
        bg.add(entryUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 340, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bienvenido");
        jLabel4.setAlignmentY(0.0F);
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        EasyChat.initCliente(this.txtIP.getText());
    }//GEN-LAST:event_btnConectarActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        EasyChat.cliente.enviarMensaje(this.entryUsuario.getText() + ": " + 
                this.txtMensaje.getText());
        this.bandejaEntrada.setText(this.bandejaEntrada.getText() +"\n"+ 
                this.entryUsuario.getText() + ": " + 
                this.txtMensaje.getText());
        this.txtMensaje.setText("");
        
    }//GEN-LAST:event_BtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JPanel LabelSendMsg;
    private javax.swing.JPanel LabelTXTMsg;
    private javax.swing.JPanel PanelMensajes;
    private javax.swing.JPanel PanelServer;
    public static javax.swing.JTextArea bandejaEntrada;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConectar;
    public javax.swing.JLabel entryUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
