package easychat;

public class VServer extends javax.swing.JFrame {

    /**
     * Creates new form VServer
     */
    public VServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        PanelServer = new javax.swing.JPanel();
        iniciarServidor = new javax.swing.JButton();
        PanelMensajes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bandejaEntrada = new javax.swing.JTextArea();
        LabelTXTMsg = new javax.swing.JPanel();
        txtMensaje = new javax.swing.JTextField();
        LabelSendMsg = new javax.swing.JPanel();
        BtnEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        entryUsuario = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Servidor");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyChat Host");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 650));
        setSize(new java.awt.Dimension(850, 600));

        bg.setBackground(new java.awt.Color(177, 166, 192));
        bg.setMinimumSize(new java.awt.Dimension(850, 600));
        bg.setPreferredSize(new java.awt.Dimension(850, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelServer.setBackground(new java.awt.Color(236, 243, 226));

        iniciarServidor.setBackground(new java.awt.Color(236, 243, 226));
        iniciarServidor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        iniciarServidor.setForeground(new java.awt.Color(51, 51, 51));
        iniciarServidor.setText("Inicia Servidor");
        iniciarServidor.setBorder(null);
        iniciarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarServidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelServerLayout = new javax.swing.GroupLayout(PanelServer);
        PanelServer.setLayout(PanelServerLayout);
        PanelServerLayout.setHorizontalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelServerLayout.setVerticalGroup(
            PanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(PanelServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 120, 40));

        PanelMensajes.setBackground(new java.awt.Color(248, 248, 248));

        bandejaEntrada.setBackground(new java.awt.Color(248, 248, 248));
        bandejaEntrada.setColumns(20);
        bandejaEntrada.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        bandejaEntrada.setRows(5);
        bandejaEntrada.setBorder(null);
        jScrollPane1.setViewportView(bandejaEntrada);

        javax.swing.GroupLayout PanelMensajesLayout = new javax.swing.GroupLayout(PanelMensajes);
        PanelMensajes.setLayout(PanelMensajesLayout);
        PanelMensajesLayout.setHorizontalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        PanelMensajesLayout.setVerticalGroup(
            PanelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        bg.add(PanelMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 750, 390));

        LabelTXTMsg.setBackground(new java.awt.Color(248, 248, 248));
        LabelTXTMsg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        LabelTXTMsg.setForeground(new java.awt.Color(248, 248, 248));

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(51, 51, 51));
        txtMensaje.setText("Introducir mensaje aqui");
        txtMensaje.setOpaque(true);
        txtMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelTXTMsgLayout = new javax.swing.GroupLayout(LabelTXTMsg);
        LabelTXTMsg.setLayout(LabelTXTMsgLayout);
        LabelTXTMsgLayout.setHorizontalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        LabelTXTMsgLayout.setVerticalGroup(
            LabelTXTMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(LabelTXTMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 650, 40));

        LabelSendMsg.setBackground(new java.awt.Color(236, 243, 226));
        LabelSendMsg.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N

        BtnEnviar.setBackground(new java.awt.Color(236, 243, 226));
        BtnEnviar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        BtnEnviar.setForeground(new java.awt.Color(51, 51, 51));
        BtnEnviar.setText("Enviar");
        BtnEnviar.setBorder(null);
        BtnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelSendMsgLayout = new javax.swing.GroupLayout(LabelSendMsg);
        LabelSendMsg.setLayout(LabelSendMsgLayout);
        LabelSendMsgLayout.setHorizontalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        LabelSendMsgLayout.setVerticalGroup(
            LabelSendMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(LabelSendMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 90, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bienvenido");
        jLabel4.setAlignmentY(0.0F);
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        entryUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        entryUsuario.setForeground(new java.awt.Color(51, 51, 51));
        entryUsuario.setAlignmentY(0.0F);
        bg.add(entryUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeActionPerformed

    private void iniciarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarServidorActionPerformed
        EasyChat.initServer();
    }//GEN-LAST:event_iniciarServidorActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        EasyChat.servidor.enviarMensaje(
                this.entryUsuario.getText() + ": " +
                this.txtMensaje.getText());
        this.bandejaEntrada.setText(this.bandejaEntrada.getText() +"\n"+ 
                this.entryUsuario.getText() + ": " + 
                this.txtMensaje.getText());
        this.txtMensaje.setText("");
    }//GEN-LAST:event_BtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JPanel LabelSendMsg;
    private javax.swing.JPanel LabelTXTMsg;
    private javax.swing.JPanel PanelMensajes;
    private javax.swing.JPanel PanelServer;
    public static javax.swing.JTextArea bandejaEntrada;
    private javax.swing.JPanel bg;
    public javax.swing.JLabel entryUsuario;
    private javax.swing.JButton iniciarServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
